# Setup
title:        帮助中心
description:  这里有新华开发平台的相关教程、规范、手册及 FAQ
baseurl:      ""
locale:       "zh-CN"
timezone:     Asia/Shanghai

#Others
markdown:     kramdown

permalink:    /article/:title.html

compress_html:
  clippings:      all
  comments:       ["<!--", "-->"]
  endings:        all
  startings:      [html, head, body]
